from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'auth_user'},
        ),
        migrations.CreateModel(
            name='RegistrationBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('typing_speed', models.FloatField(default=0)),
                ('key_hold_time', models.FloatField(default=0)),
                ('mouse_velocity', models.FloatField(default=0)),
                ('click_interval', models.FloatField(default=0)),
                ('decision_time', models.FloatField(default=0)),
                ('scroll_depth', models.FloatField(default=0)),
                ('network_latency', models.FloatField(default=0)),
                ('behavior_under_slowness', models.FloatField(default=1.0)),
                ('time_of_day', models.FloatField(default=12)),
                ('device_hash', models.CharField(blank=True, default='', max_length=64)),
                ('location_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_behavior', to='authcore.user')),
            ],
            options={'db_table': 'registration_behavior'},
        ),
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('typing_speed', models.FloatField(default=0)),
                ('key_hold_time', models.FloatField(default=0)),
                ('mouse_velocity', models.FloatField(default=0)),
                ('click_interval', models.FloatField(default=0)),
                ('decision_time', models.FloatField(default=0)),
                ('scroll_depth', models.FloatField(default=0)),
                ('network_latency', models.FloatField(default=0)),
                ('behavior_under_slowness', models.FloatField(default=1.0)),
                ('time_of_day', models.FloatField(default=12)),
                ('iki_mean', models.FloatField(default=200)),
                ('iki_std', models.FloatField(default=50)),
                ('hold_mean', models.FloatField(default=120)),
                ('hold_std', models.FloatField(default=30)),
                ('mvel_mean', models.FloatField(default=300)),
                ('mvel_std', models.FloatField(default=100)),
                ('lat_mean', models.FloatField(default=100)),
                ('lat_jitter', models.FloatField(default=20)),
                ('slow_key_ratio', models.FloatField(default=0)),
                ('device_hash', models.CharField(blank=True, default='', max_length=256)),
                ('location_hash', models.CharField(blank=True, default='', max_length=256)),
                ('trust_score', models.IntegerField(default=0)),
                ('was_trusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='authcore.user')),
            ],
            options={'db_table': 'behavior_log', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('calm', 'Calm Typing'), ('cognitive', 'Cognitive Typing'), ('controlled', 'Controlled Typing')], max_length=20)),
                ('features', models.JSONField(default=dict)),
                ('quality_score', models.FloatField(default=0.5)),
                ('duration_ms', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to='authcore.user')),
            ],
            options={'db_table': 'calibration_session', 'ordering': ['-captured_at']},
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('calm_baseline', models.JSONField(default=dict)),
                ('cognitive_baseline', models.JSONField(default=dict)),
                ('controlled_baseline', models.JSONField(default=dict)),
                ('identity_confidence', models.FloatField(default=0.3)),
                ('dynamic_threshold', models.FloatField(default=60.0)),
                ('login_count', models.IntegerField(default=0)),
                ('trusted_login_count', models.IntegerField(default=0)),
                ('consecutive_trusted', models.IntegerField(default=0)),
                ('consecutive_deviations', models.IntegerField(default=0)),
                ('typical_hours', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to='authcore.user')),
            ],
            options={'db_table': 'user_behavior_profile'},
        ),
        migrations.CreateModel(
            name='LoginRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email_attempted', models.EmailField(blank=True)),
                ('trust_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='HIGH', max_length=10)),
                ('dynamic_threshold_used', models.FloatField(default=60.0)),
                ('confidence_at_time', models.FloatField(default=0.3)),
                ('ml_score', models.FloatField(default=0)),
                ('context_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('calm_deviation', models.FloatField(default=0)),
                ('cognitive_deviation', models.FloatField(default=0)),
                ('device_matched', models.BooleanField(default=False)),
                ('location_matched', models.BooleanField(default=False)),
                ('time_anomaly', models.BooleanField(default=False)),
                ('action_taken', models.CharField(choices=[('GRANTED', 'Granted'), ('CHALLENGED', 'Challenged'), ('DENIED', 'Denied')], default='DENIED', max_length=15)),
                ('rejection_reasons', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='authcore.user')),
            ],
            options={'db_table': 'login_risk_event', 'ordering': ['-created_at']},
        ),
    ]
