# Generated by Django 5.2 on 2026-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0002_rename_behavior_lo_user_id_idx_behavior_lo_user_id_29d7ad_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behaviorlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='click_interval',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='key_hold_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='mouse_velocity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='network_latency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='scroll_depth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='time_of_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='typing_speed',
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name='behaviorlog',
            index=models.Index(fields=['device_hash'], name='behavior_lo_device__22c68c_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorlog',
            index=models.Index(fields=['location_hash'], name='behavior_lo_locatio_2b97a2_idx'),
        ),
    ]
